name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Run script
          run:  bash db.sh
